name: Frontend CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4
            - name: Install, Test, Build ${{ matrix.node-version }}
              run: |
                  npm install -g pnpm@latest
                  pnpm install
                  pnpm run build
