name: Release

on:
    # push:
    #     branches:
    #         - main # Or your release branch
    # workflow_dispatch: # Optional: allow manual trigger from GitHub UI
    workflow_run:
        workflows: ["Frontend CI"] # Must match the name in build-test.yml
        types:
            - completed

jobs:
    release:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Important for changelog generation

            - name: Install dependencies
              run: |
                  npm install -g pnpm@latest
                  pnpm install

            - name: Run release-it
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
              run: pnpm release --ci
