name: Release

on:
    workflow_run:
        workflows: ["Frontend CI"] # Must match the name in build-test.yml
        types:
            - completed

permissions:
    contents: write
jobs:
    release:
        if: >
            ${{ github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Important for changelog generation

            - name: Install dependencies
              run: |
                  npm install -g pnpm@latest
                  pnpm install

            - name: Check for uncommitted changes (debug)
              run: |
                  git status
                  git diff
            - name: Discard uncommitted changes (if any)
              run: git reset --hard

            - name: Configure Git user
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Run release-it
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm release --ci
